apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dsh-users
  namespace: dsh-poc
spec:
  accessModes: [ReadWriteMany]
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
